(function(){
  const ROUTES=['Dashboard','Projects','Groups','Vulnerabilities','POA&M','AOR','Deltas','Reports','Settings'];
  const state={payload:null,datasets:[],route:'Dashboard',page:{},filters:{q:'',severity:'',status:'',scope:'',prod:''},themeIndex:0,themes:['dark','light']};
  const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
  const esc=v=>String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=n=>Number(n||0).toLocaleString();
  const clsSev=s=>String(s||'').toLowerCase();
  const clsStatus=s=>String(s||'').includes('PRESENT')?'status-present':String(s||'').includes('RESOLVED')?'status-resolved':String(s||'').includes('NOT_APPLICABLE')?'status-na':'status-risk';
  function normalizePayload(payload){
    const projectsMap=payload.projects||{};
    const projects=Object.values(projectsMap).map(p=>({...p,project_id:String(p.project_id||''),vulnerabilities:p.vulnerabilities||[]}));
    const vulns=[]; projects.forEach(p=>(p.vulnerabilities||[]).forEach(v=>vulns.push({...v,project_id:p.project_id,project_name:p.project_name,project_path:p.project_path,parent_group:p.parent_group,namespace:p.namespace,is_prod:p.is_prod,in_scope:p.in_scope,ato_status:p.ato_status,tech_stack:p.tech_stack,owner:p.owner})));
    return {raw:payload,generatedAt:payload.generated_at,summary:payload.summary_totals||{},projects,vulns};
  }
  function current(){return state.payload || normalizePayload(window.DEFAULT_PAYLOAD||{});} 
  function scoreProject(p){const w={critical:100,high:35,medium:8,low:2};let s=0;(p.vulnerabilities||[]).forEach(v=>{if(v.reconciliation_status==='PRESENT_STILL_EXISTS')s+=w[v.severity]||1}); if(p.is_prod==='TRUE')s*=1.35; if(p.in_scope==='TRUE')s*=1.1; return Math.round(s);}
  function applyFilters(items,type){const f=state.filters; const q=f.q.toLowerCase(); return items.filter(x=>{
    const text=JSON.stringify(x).toLowerCase();
    if(q && !text.includes(q)) return false;
    if(type==='vuln'){
      if(f.severity && x.severity!==f.severity) return false;
      if(f.status && x.reconciliation_status!==f.status) return false;
      if(f.scope && x.in_scope!==f.scope) return false;
      if(f.prod && x.is_prod!==f.prod) return false;
    } else if(type==='project'){
      if(f.scope && x.in_scope!==f.scope) return false;
      if(f.prod && x.is_prod!==f.prod) return false;
      if(f.severity && !(x.vulnerabilities||[]).some(v=>v.severity===f.severity)) return false;
      if(f.status && !(x.vulnerabilities||[]).some(v=>v.reconciliation_status===f.status)) return false;
    }
    return true;
  });}
  function setTitles(t,sub){$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=sub||''; renderBreadcrumbs();}

  function breadcrumbItems(){
    if(state.route==='ProjectDetail') return [['Dashboard','/dashboard'],['Projects','/projects'],[state.params.id,null]];
    if(state.route==='GroupDetail') return [['Dashboard','/dashboard'],['Groups','/groups'],[state.params.id,null]];
    if(state.route==='VulnerabilityDetail') return [['Dashboard','/dashboard'],['Vulnerabilities','/vulnerabilities'],[state.params.id,null]];
    return [['Dashboard','/dashboard'],[state.route,null]];
  }
  function renderBreadcrumbs(){
    const el=$('#breadcrumbs'); if(!el) return;
    el.innerHTML=breadcrumbItems().map(([label,path],i)=> path?`<a href="#${path}">${esc(label)}</a><span>/</span>`:`<strong>${esc(label)}</strong>`).join('');
  }
  function renderNav(){ $('#nav').innerHTML=ROUTES.map(r=>`<button class="ghost nav-item ${state.route===r?'active':''}" data-nav="${r}" title="${r}"><span class="nav-icon">${r==='Dashboard'?'⌁':r[0]}</span><span class="nav-label">${r}</span></button>`).join(''); }
  function navigate(route, params={}){state.route=route;state.params=params;renderNav();render();}
  function routeFromHash(){const h=location.hash.replace(/^#\/?/,''); if(h.startsWith('project/')) return navigate('ProjectDetail',{id:h.split('/')[1]}); if(h.startsWith('group/')) return navigate('GroupDetail',{id:decodeURIComponent(h.slice(6))}); if(h.startsWith('vulnerability/')) return navigate('VulnerabilityDetail',{id:h.split('/')[1]}); const r=ROUTES.find(x=>x.toLowerCase()===h.toLowerCase()); if(r) navigate(r);}
  function setHash(path){location.hash=path;}
  function kpis(){const d=current(); const s=d.summary; const statuses=s.statuses||{}; const prod=s.prod_projects ?? d.projects.filter(p=>p.is_prod==='TRUE').length; const active=statuses.PRESENT_STILL_EXISTS ?? d.vulns.filter(v=>v.reconciliation_status==='PRESENT_STILL_EXISTS').length; const health=Math.max(0,Math.round(100-(active/Math.max(1,s.total_vulnerabilities||d.vulns.length))*100)); return [
    ['Projects Scanned',s.total_projects_scanned||d.projects.length,'Repository inventory baseline'],['In Scope',s.in_scope_count||d.projects.filter(p=>p.in_scope==='TRUE').length,'Governance included projects'],['Prod Projects',prod,'Production impacting'],['Parent Groups',new Set(d.projects.map(p=>p.parent_group)).size,'Namespace families'],['Total Vulns',s.total_vulnerabilities||d.vulns.length,'Snapshot reconciled count'],['Security Health',health,'Derived from active findings']
  ].map(x=>`<div class="card"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${fmt(x[1])}</div><div class="kpi-note">${x[2]}</div></div>`).join('');}
  function lifecycle(){const st=current().summary.statuses||{}; const total=Object.values(st).reduce((a,b)=>a+Number(b||0),0)||1; const colors=['#ff8fa3','#5df0b2','#c4d3e8','#caa8ff']; const keys=['PRESENT_STILL_EXISTS','RESOLVED','NOT_APPLICABLE_OUT_OF_SCOPE','DISMISSED_ACCEPTED_RISK']; return `<div class="panel chart-card"><h3>Vulnerability Lifecycle</h3><p>Actual reconciled states from dataset</p><div class="stack">${keys.map((k,i)=>`<span title="${k}" style="width:${(st[k]||0)/total*100}%;background:${colors[i]}"></span>`).join('')}</div><div class="legend">${keys.map((k,i)=>`<span><i class="dot" style="background:${colors[i]}"></i>${k}: ${fmt(st[k]||0)}</span>`).join('')}</div></div>`;}
  function severity(){const counts={critical:0,high:0,medium:0,low:0}; current().vulns.forEach(v=>{if(v.reconciliation_status==='PRESENT_STILL_EXISTS')counts[v.severity]=(counts[v.severity]||0)+1}); const max=Math.max(1,...Object.values(counts)); return `<div class="panel chart-card"><h3>Severity Distribution</h3><p>Click a severity to open the filtered vulnerability workbench</p><div class="list">${Object.entries(counts).map(([k,v])=>`<button class="risk-row metric-link severity-row" data-severity-filter="${k}" type="button"><strong class="${k}">${k}</strong><div class="bar"><span style="width:${v/max*100}%"></span></div><b>${fmt(v)}</b></button>`).join('')}</div></div>`;}
  function groupHeat(){const groups={}; current().projects.forEach(p=>{const g=p.parent_group||'UNKNOWN'; groups[g]=groups[g]||{projects:0,prod:0,score:0}; groups[g].projects++; if(p.is_prod==='TRUE')groups[g].prod++; groups[g].score+=scoreProject(p)}); const rows=Object.entries(groups).sort((a,b)=>b[1].score-a[1].score).slice(0,10); const max=Math.max(1,...rows.map(r=>r[1].score)); return `<div class="panel chart-card"><h3>Parent Group Risk Heatmap</h3><p>Click group to drill down</p><div class="list">${rows.map(([g,x])=>`<div class="risk-row" data-group="${esc(g)}"><strong>${esc(g)}</strong><div><div class="bar"><span style="width:${x.score/max*100}%"></span></div><small class="muted">${x.projects} projects • ${x.prod} prod</small></div><b>${fmt(x.score)}</b></div>`).join('')}</div></div>`;}
  function topRisk(){const rows=current().projects.map(p=>({...p,score:scoreProject(p)})).sort((a,b)=>b.score-a.score).slice(0,8); const max=Math.max(1,...rows.map(r=>r.score)); return `<div class="panel chart-card"><h3>Top Risk Projects</h3><p>Click project to open detail page</p><div class="list">${rows.map(p=>`<div class="risk-row" data-project-id="${p.project_id}"><strong>${esc(p.project_name)}</strong><div><div class="bar"><span style="width:${p.score/max*100}%"></span></div><small class="muted">${esc(p.project_path)}</small></div><b>${fmt(p.score)}</b></div>`).join('')}</div></div>`;}
  function dashboard(){setTitles('Executive Dashboard','Purpose-built portfolio overview. No fake monthly trend unless multiple snapshots are loaded.'); $('#view').innerHTML=`<div class="grid kpis">${kpis()}</div><div class="split">${lifecycle()}${severity()}</div><div class="split">${groupHeat()}${topRisk()}</div>${snapshotPanel()}`;}
  function snapshotPanel(){return `<div class="panel chart-card"><h3>Snapshot Trend</h3><p>${state.datasets.length<2?'No historical datasets loaded. Load multiple JSON snapshots to enable delta and trend analysis.':'Multiple datasets loaded. Use Deltas to compare changes.'}</p></div>`}
  function paginate(key,items,renderRow,headers){const page=state.page[key]||1; const size=Number(localStorage.getItem('pageSize')||25); const pages=Math.max(1,Math.ceil(items.length/size)); const safe=Math.min(page,pages); state.page[key]=safe; const slice=items.slice((safe-1)*size,safe*size); return `<div class="table-panel"><div class="table-toolbar"><strong>${fmt(items.length)} records</strong><div><select data-page-size><option ${size===25?'selected':''}>25</option><option ${size===50?'selected':''}>50</option><option ${size===100?'selected':''}>100</option></select></div></div><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${slice.map(renderRow).join('')}</tbody></table></div><div class="pager"><button class="ghost small" data-page-key="${key}" data-page="${safe-1}" ${safe<=1?'disabled':''}>Prev</button><span class="muted">Page ${safe} / ${pages}</span><button class="ghost small" data-page-key="${key}" data-page="${safe+1}" ${safe>=pages?'disabled':''}>Next</button></div></div>`}
  function projects(){setTitles('Projects','Canonical project inventory from payload.projects object/map.'); const rows=applyFilters(current().projects,'project'); $('#view').innerHTML=paginate('projects',rows,p=>`<tr><td><a class="link" href="#/project/${p.project_id}">${esc(p.project_name)}</a><br><small class="muted">${esc(p.project_path)}</small></td><td>${esc(p.parent_group)}</td><td>${badge(p.in_scope)}</td><td>${badge(p.is_prod)}</td><td>${esc(p.ato_status)}</td><td>${esc(p.tech_stack)}</td><td>${fmt((p.vulnerabilities||[]).length)}</td><td>${linkOut(p.gitlab_url,'GitLab')}</td></tr>`,['Project','Parent Group','Scope','Prod','ATO','Tech Stack','Vulns','Links']);}
  function groups(){setTitles('Groups','Parent group and namespace drilldowns.'); const map={}; applyFilters(current().projects,'project').forEach(p=>{const g=p.parent_group||'UNKNOWN'; map[g]=map[g]||{g,projects:0,prod:0,vulns:0,score:0}; map[g].projects++; if(p.is_prod==='TRUE')map[g].prod++; map[g].vulns+=(p.vulnerabilities||[]).length; map[g].score+=scoreProject(p)}); const rows=Object.values(map).sort((a,b)=>b.score-a.score); $('#view').innerHTML=paginate('groups',rows,g=>`<tr><td><a class="link" href="#/group/${encodeURIComponent(g.g)}">${esc(g.g)}</a></td><td>${fmt(g.projects)}</td><td>${fmt(g.prod)}</td><td>${fmt(g.vulns)}</td><td>${fmt(g.score)}</td></tr>`,['Parent Group','Projects','Prod','Vulns','Risk']);}
  function vulnerabilities(){setTitles('Vulnerabilities','Finding workbench with evidence links and project drilldowns.'); const rows=applyFilters(current().vulns,'vuln'); $('#view').innerHTML=paginate('vulns',rows,v=>`<tr><td><a class="link ${clsSev(v.severity)}" href="#/vulnerability/${v.vulnerability_id}">${esc(v.cve||v.vulnerability_id)}</a><br><small>${esc(v.package||'')}</small></td><td class="${clsSev(v.severity)}">${esc(v.severity)}</td><td class="${clsStatus(v.reconciliation_status)}">${esc(v.reconciliation_status)}</td><td><a class="link" href="#/project/${v.project_id}">${esc(v.project_name)}</a></td><td>${esc(v.parent_group)}</td><td>${esc(v.scanner||'')}</td><td>${esc(v.verified_at||'')}</td><td>${linkOut(v.evidence_location_url,'Evidence')}</td></tr>`,['CVE','Severity','Status','Project','Parent Group','Scanner','Verified','Evidence']);}
  function projectDetail(){const id=state.params.id; const p=current().raw.projects?.[id] || current().projects.find(x=>x.project_id===id); if(!p){$('#view').innerHTML='<div class="panel chart-card">Project not found.</div>'; return} setTitles(p.project_name, p.project_path); const active=(p.vulnerabilities||[]).filter(v=>v.reconciliation_status==='PRESENT_STILL_EXISTS'); $('#view').innerHTML=`<div class="detail-grid">${[['Project ID',p.project_id],['Parent Group',p.parent_group],['ATO',p.ato_status],['Prod',p.is_prod],['In Scope',p.in_scope],['Tech Stack',p.tech_stack],['Risk Score',scoreProject(p)],['Owner',p.owner||'Unknown']].map(x=>`<div class="card"><div class="kpi-label">${x[0]}</div><div class="kpi-value" style="font-size:20px">${esc(x[1])}</div></div>`).join('')}</div><div class="tabs"><a class="button" target="_blank" href="${esc(p.gitlab_url||'#')}">Open GitLab</a><a class="button" target="_blank" href="${esc(p.pipeline_url||'#')}">Pipelines</a><a class="button" target="_blank" href="${esc(p.container_registry_url||'#')}">Registry</a></div>${paginate('projectVulns'+id,p.vulnerabilities||[],v=>`<tr><td><a class="link" href="#/vulnerability/${v.vulnerability_id}">${esc(v.cve)}</a></td><td class="${clsSev(v.severity)}">${esc(v.severity)}</td><td class="${clsStatus(v.reconciliation_status)}">${esc(v.reconciliation_status)}</td><td>${esc(v.package||'')}</td><td>${esc(v.policy_justification_notes||'')}</td><td>${linkOut(v.evidence_location_url,'Evidence')}</td></tr>`,['CVE','Severity','Status','Package','Notes','Evidence'])}`; inspectProject(p);}
  function groupDetail(){const id=state.params.id; const rows=current().projects.filter(p=>p.parent_group===id); setTitles(id,`${rows.length} projects in parent group`); $('#view').innerHTML=paginate('groupProjects'+id,rows,p=>`<tr><td><a class="link" href="#/project/${p.project_id}">${esc(p.project_name)}</a></td><td>${badge(p.is_prod)}</td><td>${badge(p.in_scope)}</td><td>${esc(p.ato_status)}</td><td>${fmt((p.vulnerabilities||[]).length)}</td><td>${fmt(scoreProject(p))}</td></tr>`,['Project','Prod','Scope','ATO','Vulns','Risk']);}
  function vulnDetail(){const id=state.params.id; const v=current().vulns.find(x=>x.vulnerability_id===id); if(!v){$('#view').innerHTML='<div class="panel chart-card">Vulnerability not found.</div>'; return} setTitles(v.cve||v.vulnerability_id,`Finding ${v.vulnerability_id}`); $('#view').innerHTML=`<div class="detail-grid">${[['Severity',v.severity],['Status',v.reconciliation_status],['Project',v.project_name],['Scanner',v.scanner],['Package',v.package],['Verified',v.verified_at],['Prod',v.is_prod],['Scope',v.in_scope]].map(x=>`<div class="card"><div class="kpi-label">${x[0]}</div><div class="kpi-value" style="font-size:18px">${esc(x[1])}</div></div>`).join('')}</div><div class="panel chart-card" style="margin-top:16px"><h3>Evidence & Remediation</h3><p>${esc(v.policy_justification_notes||'')}</p><p><strong>Suggested remediation:</strong> ${esc(v.remediation||'Review vendor guidance and rebuild from patched approved base image.')}</p><p>${linkOut(v.evidence_location_url,'Open GitLab Evidence')}</p><div class="code">${esc(JSON.stringify(v,null,2))}</div></div>`; inspectVuln(v);}
  function poam(){setTitles('POA&M Manager','Generate actionable remediation backlog from active findings.'); const rows=applyFilters(current().vulns.filter(v=>v.reconciliation_status==='PRESENT_STILL_EXISTS'),'vuln'); $('#view').innerHTML=`<div class="actions"><button class="primary" data-export="poam">Export POA&M CSV</button></div>`+paginate('poam',rows,v=>`<tr><td>${esc(v.cve)}</td><td class="${clsSev(v.severity)}">${esc(v.severity)}</td><td><a class="link" href="#/project/${v.project_id}">${esc(v.project_name)}</a></td><td>${esc(v.owner||'Application Team')}</td><td>${esc(v.remediation||'Patch or mitigate')}</td><td>${targetDate(v.severity)}</td><td>${linkOut(v.evidence_location_url,'Evidence')}</td></tr>`,['Finding','Severity','Project','AOR','Recommended Action','Target Date','Evidence']);}
  function aor(){setTitles('AOR Mapping','Ownership and area-of-responsibility rollups.'); const map={}; current().projects.forEach(p=>{const o=p.owner||'Unknown'; map[o]=map[o]||{owner:o,projects:0,prod:0,active:0}; map[o].projects++; if(p.is_prod==='TRUE')map[o].prod++; map[o].active+=(p.vulnerabilities||[]).filter(v=>v.reconciliation_status==='PRESENT_STILL_EXISTS').length}); const rows=Object.values(map); $('#view').innerHTML=paginate('aor',rows,r=>`<tr><td>${esc(r.owner)}</td><td>${fmt(r.projects)}</td><td>${fmt(r.prod)}</td><td>${fmt(r.active)}</td><td>${r.active? 'Needs remediation coordination':'No active findings'}</td></tr>`,['AOR','Projects','Prod','Active Findings','Guidance']);}
  function deltas(){setTitles('Deltas','Load multiple JSON snapshots to compare changes.'); $('#view').innerHTML=`<div class="panel chart-card"><h3>Loaded Datasets</h3><p>${state.datasets.length} dataset(s) loaded.</p>${state.datasets.map((d,i)=>`<div class="risk-row"><strong>${esc(d.raw.dataset_name||'Dataset '+(i+1))}</strong><span>${esc(d.generatedAt)}</span><b>${fmt(d.vulns.length)}</b></div>`).join('')||'<p>No additional snapshots loaded.</p>'}</div>`}
  function reports(){setTitles('Reports','Leadership, security engineer, POA&M and AOR report exports.'); $('#view').innerHTML=`<div class="grid" style="grid-template-columns:repeat(2,minmax(240px,1fr))"><div class="card"><h3>Leadership Brief</h3><p>Portfolio risk summary by group, prod exposure, and lifecycle status.</p><button data-report="leadership">Generate Markdown</button></div><div class="card"><h3>Security Engineer Report</h3><p>Detailed project and vulnerability evidence report.</p><button data-report="engineer">Generate Markdown</button></div><div class="card"><h3>POA&M Export</h3><p>Active findings transformed into remediation backlog.</p><button data-export="poam">Export CSV</button></div><div class="card"><h3>AOR Report</h3><p>Ownership rollup by team/system area.</p><button data-report="aor">Generate Markdown</button></div></div><div id="reportOutput" class="panel chart-card" style="margin-top:16px"></div>`}
  function settings(){setTitles('Settings','Configurable rules, page size, theme, and local workspace behavior.'); $('#view').innerHTML=`<div class="panel chart-card"><h3>Configuration</h3><p>Canonical schema: generated_at, summary_totals, projects object/map, vulnerabilities array per project.</p><label>Default page size<select id="pageSizeSetting"><option>25</option><option>50</option><option>100</option></select></label><p class="muted">Theme and page size are stored locally in browser storage.</p></div>`; const ps=$('#pageSizeSetting'); ps.value=localStorage.getItem('pageSize')||25; ps.onchange=()=>{localStorage.setItem('pageSize',ps.value);render()};}
  function badge(v){return `<span class="badge">${esc(v)}</span>`}
  function linkOut(url,label){return url?`<a class="link" target="_blank" rel="noopener" href="${esc(url)}">${label} ↗</a>`:'<span class="muted">N/A</span>'}
  function targetDate(sev){const days={critical:15,high:30,medium:90,low:180}[sev]||90; const d=new Date(); d.setDate(d.getDate()+days); return d.toISOString().slice(0,10)}
  function inspectProject(p){$('#inspectorBody').innerHTML=`<h3>${esc(p.project_name)}</h3><p>${esc(p.project_path)}</p><div class="code">${esc(JSON.stringify({project_id:p.project_id,parent_group:p.parent_group,ato_status:p.ato_status,is_prod:p.is_prod,in_scope:p.in_scope,tech_stack:p.tech_stack,risk_score:scoreProject(p)},null,2))}</div>`}
  function inspectVuln(v){$('#inspectorBody').innerHTML=`<h3>${esc(v.cve)}</h3><p>${esc(v.reconciliation_status)}</p><div class="code">${esc(JSON.stringify(v,null,2))}</div>`}
  function render(){const routes={Dashboard:dashboard,Projects:projects,Groups:groups,Vulnerabilities:vulnerabilities,'ProjectDetail':projectDetail,'GroupDetail':groupDetail,'VulnerabilityDetail':vulnDetail,'POA&M':poam,AOR:aor,Deltas:deltas,Reports:reports,Settings:settings}; (routes[state.route]||dashboard)(); updateBadge(); bindDynamic();}
  function updateBadge(){const d=current(); $('#datasetBadge').innerHTML=`Active: ${esc(d.raw.dataset_name||'Loaded dataset')}<br>Datasets: ${state.datasets.length||1}`}
  function bindDynamic(){ $$('[data-severity-filter]').forEach(el=>el.onclick=e=>{e.preventDefault(); state.filters.severity=el.dataset.severityFilter; const sf=$('#severityFilter'); if(sf) sf.value=state.filters.severity; state.page={}; setHash('/vulnerabilities')}); $$('[data-project-id]').forEach(el=>el.onclick=e=>{e.preventDefault(); setHash('/project/'+el.dataset.projectId)}); $$('[data-group]').forEach(el=>el.onclick=e=>{e.preventDefault(); setHash('/group/'+encodeURIComponent(el.dataset.group))}); $$('[data-page-key]').forEach(b=>b.onclick=()=>{state.page[b.dataset.pageKey]=Number(b.dataset.page);render()}); $$('[data-page-size]').forEach(s=>s.onchange=()=>{localStorage.setItem('pageSize',s.value);state.page={};render()}); $$('[data-collapse-target]').forEach(b=>b.onclick=()=>$('#'+b.dataset.collapseTarget).classList.toggle('collapsible-hidden')); $$('[data-report]').forEach(b=>b.onclick=()=>generateReport(b.dataset.report)); $$('[data-export="poam"]').forEach(b=>b.onclick=exportPoam); }
  function generateReport(type){const d=current(); const text=`# ${type.toUpperCase()} Report\n\nGenerated: ${new Date().toISOString()}\n\nProjects scanned: ${d.summary.total_projects_scanned||d.projects.length}\nIn scope: ${d.summary.in_scope_count||d.projects.filter(p=>p.in_scope==='TRUE').length}\nTotal vulnerabilities: ${d.summary.total_vulnerabilities||d.vulns.length}\nActive findings: ${(d.summary.statuses||{}).PRESENT_STILL_EXISTS||0}\n`; $('#reportOutput').innerHTML=`<h3>Generated ${esc(type)} report</h3><textarea rows="12">${esc(text)}</textarea><button onclick="navigator.clipboard.writeText(document.querySelector('#reportOutput textarea').value)">Copy</button>`}
  function exportPoam(){const rows=current().vulns.filter(v=>v.reconciliation_status==='PRESENT_STILL_EXISTS'); const csv=['cve,severity,project,aor,recommendation,target_date,evidence'].concat(rows.map(v=>[v.cve,v.severity,v.project_name,v.owner||'Application Team',v.remediation||'',targetDate(v.severity),v.evidence_location_url||''].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','))).join('\n'); download('poam_export.csv',csv,'text/csv')}
  function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function loadPayload(p,name){state.payload=normalizePayload(p);state.datasets.push(state.payload);state.rawName=name;render();}
  function debounce(fn,ms){let t;return (...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
  function bindStatic(){renderNav(); $('#nav').onclick=e=>{const b=e.target.closest('[data-nav]'); if(b){setHash('/'+b.dataset.nav.toLowerCase())}}; window.addEventListener('hashchange',routeFromHash); $('#collapseSidebar').onclick=()=>{ $('#sidebar').classList.toggle('collapsed'); $('#shell').classList.toggle('sidebar-collapsed'); $('#collapseSidebar').textContent=$('#sidebar').classList.contains('collapsed')?'☰':'☰ Collapse'; }; $('#closeInspector').onclick=()=>$('#inspector').classList.toggle('closed'); $('#themeToggle').onclick=()=>{state.themeIndex=(state.themeIndex+1)%state.themes.length;document.body.dataset.theme=state.themes[state.themeIndex];$('#themeToggle').textContent=state.themes[state.themeIndex]==='dark'?'Light Mode':'Dark Mode'}; $('#fileInput').onchange=async e=>{for(const f of e.target.files){const p=JSON.parse(await f.text());loadPayload(p,f.name)}}; $('#saveLocal').onclick=()=>{localStorage.setItem('securityPlatformDataset',JSON.stringify(current().raw));alert('Dataset saved to local browser storage.')}; $('#exportDataset').onclick=()=>download('dashboard_payload_export.json',JSON.stringify(current().raw,null,2)); const deb=debounce(()=>{state.filters.q=$('#globalSearch').value; state.page={}; render()},180); $('#globalSearch').addEventListener('input',deb); ['severityFilter','statusFilter','scopeFilter','prodFilter'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.filters[id.replace('Filter','')==="severity"?'severity':id.replace('Filter','')==="status"?'status':id.replace('Filter','')==="scope"?'scope':'prod']=$('#'+id).value;state.page={};render()})); document.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable)e.preventDefault()});}
  async function boot(){bindStatic(); try{const saved=localStorage.getItem('securityPlatformDataset'); if(saved){loadPayload(JSON.parse(saved),'local'); return;} const res=await fetch('data/synthetic_dashboard_payload.json'); if(res.ok){loadPayload(await res.json(),'synthetic');return}}catch(e){} render(); routeFromHash();}
  boot();
})();
